# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fluent-plugin-mongo}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Masahiro Nakagawa"]
  s.date = %q{2011-10-02}
  s.email = %q{repeatedly@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "AUTHORS",
    "Rakefile",
    "VERSION",
    "lib/fluent/plugin/out_mongo.rb"
  ]
  s.homepage = %q{http://github.com/fluent}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{MongoDB output plugin for Fluent event collector}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<fluent>, ["~> 0.9.14"])
      s.add_runtime_dependency(%q<mongo>, [">= 1.2.0"])
    else
      s.add_dependency(%q<fluent>, ["~> 0.9.14"])
      s.add_dependency(%q<mongo>, [">= 1.2.0"])
    end
  else
    s.add_dependency(%q<fluent>, ["~> 0.9.14"])
    s.add_dependency(%q<mongo>, [">= 1.2.0"])
  end
end

