name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 1 * *'
jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.7
  build:
    needs: ruby-versions
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.ruby == 'head' }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        mongodb-version: ['5.0', '4.4', '4.2']
        os:
          - ubuntu-latest

    name: Ruby ${{ matrix.ruby }} and MongoDB ${{ matrix.mongodb-version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: ruby/setup-ruby@4dc28cf14d77b0afa6832d9765ac422dbf0dfedd # v1.298.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@538a4d2a1041920c47630172445cb688592d6e51 # v1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: unit testing
      env:
        CI: true
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake test
