name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 1 * *'
jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.7
  build:
    needs: ruby-versions
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.ruby == 'head' }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        mongodb-version: ['8.0', '7.0', '6.0', '5.0', '4.4', '4.2']
        os:
          - ubuntu-latest

    name: Ruby ${{ matrix.ruby }} and MongoDB ${{ matrix.mongodb-version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94 # v1.12.1
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: unit testing
      env:
        CI: true
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake test
